### ISSUE TITLE
catch redirect response server

### ISSUE THREAD

**Issue by centratelemedia** [lesismal/pmjs#2]
is possible to pmjs catch redirect response from server? when user click refresh button of browser

**Comment by lesismal** [comment]
pm will parse url when the user clicks refresh button of browser, then handle it according to the router:
https://github.com/lesismal/pmjs/blob/master/examples/bind_src_dst/js/pm.js#L214

And I just made some commit:
add `onload` to handle event of url resource loaded;
then `onshow` will just handle the event when the page is displayed.

I also add redirect response in [examples/server.go](https://github.com/lesismal/pmjs/blob/master/examples/server.go), for more details, you can try the examples at:
http://localhost:8081/redirect
Then you can check the console log and see how it handles redirect/refresh.

**Comment by centratelemedia** [comment]
@lesismal thank you very much, really appreciate your work, but can we add same header before load, i have issue attach token when use click refresh button.....

**Comment by centratelemedia** [comment]
temporary solution add param token like /map?token=64384949djhsdkdddkdlk
